apiVersion: v2
name: eth-balance-exporter
description: A Helm chart for deploying eth-metrics-exporter
type: application
version: 0.1.0
appVersion: "1.0.0"
#dependencies:
#  - name: kube-prometheus-stack
#    repository: https://prometheus-community.github.io/helm-charts
#    version: 48.0.0
#
